services:
  vscode:
    build: .
    container_name: vscode_container
    restart: unless-stopped
    ports:
      - "8080:8080"  # Porta do VS Code Server
      - "22:22"      # Porta do SSH
    volumes:
      - ./code-server-data:/home/usr_vscode
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - PASSWORD=1234 #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=1234 #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
